// examples/vue-hmr/App.vue
<template>
  <div className="App">
    <header className="App-header">
      <h1>Hello Rolldown + Vue</h1>
      <Button />
      <p>Edit <code>App.vue</code> and save to test HMR updates.</p>
      <a
        className="App-link"
        href="https://vuejs.org/guide/introduction.html"
        target="_blank"
        rel="noopener noreferrer"
      >
        Learn Vue
      </a>
    </header>
  </div>
</template>

<script setup>
import Button from './Button.vue'
</script>

// examples/react-hmr/src/App.tsx
import { useState } from 'react'

function App() {
  const [count, setCount] = useState(0)

  return (
    <>
      <div>
        <a href="https://vite.dev" target="_blank"></a>
        <a href="https://react.dev" target="_blank">
          {/* <img src={reactLogo} className="logo react" alt="React logo" /> */}
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
    </>
  )
}

export default App
