// examples/vue-hmr/App.vue
<template>
  <div className="App">
    <header className="App-header">
      <h1>Hello Rolldown + Vue</h1>
      <Button />
      <p>Edit <code>App.vue</code> and save to test HMR updates.</p>
      <a
        className="App-link"
        href="https://vuejs.org/guide/introduction.html"
        target="_blank"
        rel="noopener noreferrer"
      >
        Learn Vue
      </a>
    </header>
  </div>
</template>

<script setup>
import Button from './Button.vue'
</script>

// examples/react-hmr/App.jsx
import React from 'react'
import Button from './Button'

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <h1>Hello Rolldown + React</h1>
        <Button />
        <p>
          Edit <code>App.jsx</code> and save to test HMR updates.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  )
}

export default App
